### ISSUE TITLE
break STIGs out into seperate repos

### ISSUE THREAD

**Issue by paulczar** [paulczar/inspec-stigs#7]
Since we're now under a org ...  maybe each STIG should get its own repo ?   we can leave the common tools ( shitty scripts? ) etc in here for now and maybe rename it.

**Comment by paulczar** [comment]
example - https://github.com/inspec-stigs/inspec-stig-rhel6

**Comment by pburkholder** [comment]
Yes, each STIG needs it's own repo so it plays nicely with the `.kitchen.yml` remote profile setup.  E.g., from the README at https://github.com/chef/kitchen-inspec:

```
suites:
  - name: contains_inspec
    run_list:
      - recipe[apt]
      - recipe[yum]
      - recipe[ssh-hardening]
      - recipe[os-hardening]
    verifier:
      inspec_tests:
        - https://github.com/dev-sec/tests-ssh-hardening
        - https://github.com/dev-sec/tests-os-hardening
```

The top-level repo needs to have `controls/`, etc. 

Also, I think for sanity it's better to have core tooling in one repo, then the profiles themselves in separate repos w/ their own issues.
